name: deploy_for_chat

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PAT_TOKEN }}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SECRET_KEY }}
          script: |
            cd /root/project/api-admin-marketplace
            git fetch --all
            git checkout master
            git pull https://${{ secrets.PAT_TOKEN }}@github.com/andreyDanilenko/admin-panel-golang.git master
            docker-compose down
            docker-compose up -d --build