name: deploy_for_chat

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PAT_TOKEN }}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SECRET_KEY }}
          script: |
            cd /root/project/api-admin-marketplace || exit 1

            # Настройка SSH для работы с GitHub
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_keys
            ssh -T git@github.com  # Проверка подключения

            # Добавляем основной репозиторий как upstream (если ещё не добавлен)
            if ! git remote | grep -q upstream; then
              git remote add upstream git@github.com:andreyDanilenko/admin-panel-golang.git
            fi

            # Получаем все изменения
            git fetch --all

            # Переключаемся на master и жестко сбрасываем его до upstream/master
            git checkout master
            git reset --hard upstream/master

            # Принудительно синхронизируем с origin (если нужно)
            git push --force origin master

            # Перезапускаем контейнеры
            docker-compose down
            docker-compose up -d --build

            echo "Деплой завершён. Master синхронизирован с основным репозиторием."